# Lazy dependencies - installed only when heavy modules are loaded
[deps]
Redis = "0cf705f9-a9e2-50d1-a699-2b372a39b750"

[sources]  
Redis = {url = "https://github.com/JuliaDatabases/Redis.jl"}

[compat]
Redis = "3"